# This config runs Home Assistant and Matter
# the Mosquitto and Z2M instances are in their own containers under z2m.

networks:
  # Allow access from Internet over Cloudflare, works great 
  # but blocks local network access so all IP connected devices become unavailable.
#  warp:
#    name: zero-trust
#    external: true
  # Internal network for HA and Z2M
  homeassistant:
    name: homeassistant
    external: true

services:
  server:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - ${PWD}/config:/config
    ports:
      - "80:80"
      - "22222:22222" # ssh (debug only)
      - "5683:5683" # CoIot for Shelly 1
      - "8123:8123" # For Wyoming
    environment:
      TZ: "America/Los_Angeles"
    restart: unless-stopped
    networks:
      - homeassistant

  matter:
    image: ghcr.io/matter-js/python-matter-server:stable
    environment:
      TZ: "America/Los_Angeles"
    security_opt:
      # Required for Bluetooth via D-Bus
      - apparmor:unconfined
    volumes:
      - ${PWD}/matter_data:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    ports:
      - "5580:5580"
    networks:
      homeassistant:
        aliases:
          - matter
