FROM nodered/node-red:latest

RUN npm install node-red-contrib-home-assistant-websocket
RUN npm install node-red-contrib-sunevents
RUN npm install node-red-contrib-bigtimer
RUN npm install node-red-contrib-timeout
RUN npm audit fix