kitchen_light_toggle:
  sequence:
  - type: turn_off
    device_id: b3f289d7fab485b931ec614c62fdc055
    entity_id: 9daeed9681c17a209b6ff3d59a851fab
    domain: light
  alias: Kitchen light toggle
  description: ''
